sudo: false
services:
  - docker
install:
  - docker build -t terraform-nanny:local .
before_script:
  - cd example/tf-10-region && docker run -v `pwd`:/src --entrypoint "pwd" terraform-nanny:local cd /src && terraform workspace new production && terraform workspace new test
script:
  - cd example && docker run -v `pwd`:/src terraform-nanny:local
