sudo: false
python:
  - 3.6
install:
  - curl -fSL "https://releases.hashicorp.com/terraform/0.10.7/terraform_0.10.7_linux_amd64.zip" -o terraform.zip
  - sudo unzip terraform.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  - rm -f terraform.zip
  - cp terraform-nanny.py example/
script: cd example && python terraform-nanny.py